#ifndef __GUIMyFrame__
#define __GUIMyFrame__

/**
@file
Subclass of MyFrame, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include <memory>

class ConfigClass;

/** Implementing MyFrame */
class GUIMyFrame : public MyFrame
{
	protected:
		// Handlers for MyFrame events.
		void drawing_panelUpdate( wxUpdateUIEvent& event );
		void function_choiceOnChoice( wxCommandEvent& event );
		void load_buttonOnButtonClick( wxCommandEvent& event );
		void draw_buttonOnButtonClick( wxCommandEvent& event );
		void contour_checkBoxOnCheckBox( wxCommandEvent& event );
		void zoom_sliderOnScroll( wxScrollEvent& event );
		void x_sliderOnScroll( wxScrollEvent& event );
		void y_sliderOnScroll( wxScrollEvent& event );
		void z_sliderOnScroll( wxScrollEvent& event );
		void save_buttonOnButtonClick( wxCommandEvent& event );
		void print_buttonOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame( wxWindow* parent );
	//// end generated class members
		~GUIMyFrame() {};
		std::shared_ptr<ConfigClass> cfg;
		void Repaint();

};

#endif // __GUIMyFrame__
