#ifndef __GUIMyFrame__
#define __GUIMyFrame__

/**
@file
Subclass of MyFrame, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include <memory>

class ConfigClass;

/** Implementing MyFrame */
class GUIMyFrame : public MyFrame
{
	protected:
		// Handlers for MyFrame events.
		void drawing_panelUpdate( wxUpdateUIEvent& event );
		void function_choiceOnChoice( wxCommandEvent& event );
		void load_buttonOnButtonClick( wxCommandEvent& event );
		void x0_update( wxCommandEvent& event );
		void y0_update( wxCommandEvent& event );
		void z0_update( wxCommandEvent& event );
		void x1_update( wxCommandEvent& event );
		void y1_update( wxCommandEvent& event );
		void z1_update( wxCommandEvent& event );
		void draw_buttonOnButtonClick( wxCommandEvent& event );
		void contour_checkBoxOnCheckBox( wxCommandEvent& event );
		void zoom_sliderOnScroll( wxScrollEvent& event );
		void x_sliderOnScroll( wxScrollEvent& event );
		void y_sliderOnScroll( wxScrollEvent& event );
		void z_sliderOnScroll( wxScrollEvent& event );
		void save_buttonOnButtonClick( wxCommandEvent& event );
		void print_buttonOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame( wxWindow* parent );
	//// end generated class members
		~GUIMyFrame() {};
		std::shared_ptr<ConfigClass> cfg;
		void Repaint();









};
/*
klasa pomocnicza wraz z metodami. Potrzebna do wydrukowania 
Wrzucilem tutaj bo nie wiem gdzie indziej
*/
class Printout : public wxPrintout, public GUIMyFrame
{
public:
	Printout(const wxChar* title = (const wxChar*)"Mój wydruk") :wxPrintout(title), GUIMyFrame(NULL) {};
	bool OnPrintPage(int page);
	bool OnBeginDocument(int startPage, int endPage);
	void GetPageInfo(int* minPage, int* maxPage, int* selPageFrom, int* selPageTo);
};
#endif // __GUIMyFrame__

